### PR TITLE
Fix manual page formatting

### PR DESCRIPTION
**Pull request by tobiolo**
Remove brackets and custom link style

### CODE REVIEW

**Review by lauft — CHANGES_REQUESTED** [review]
The asciidoc documents are also used for the HTML documentation on timewarrior.net (👉🏻 https://timewarrior.net/reference/timew.1/).
While the man pages are unchanged, formatting the links like this makes them no longer clickable in HTML.

**Comment by tobiolo** [comment]
> The asciidoc documents are also used for the HTML documentation on timewarrior.net (👉🏻 https://timewarrior.net/reference/timew.1/). While the man pages are unchanged, formatting the links like this makes them no longer clickable in HTML.

Thanks for your feedback. I removed the brackets then and also the custom linkstyle settings for the AsciiDoctor.

Now this looks better for me:
image

**Review by lauft — APPROVED** [review]

**Comment by lauft** [comment]
Thank you for your contribution. ❤️

**Comment by tobiolo** [comment]
> Thank you for your contribution. ❤️ 

You are welcome!

**Pull request merged**
