### PR TITLE
Fix segfaults on join command and invalid tags database.

### PR DESCRIPTION
**Pull request by sruffell**
Two commits that eliminate segment faults when attempting to join intervals and when the tags database is missing "count" member for a particular tag name.

### CODE REVIEW

**Comment by sruffell** [comment]
Hmm...my branch name is bad. It should be for 2_0_0.

**Comment by lauft** [comment]
1.2.0 is a remnant of the old practice to start a new branch with the next upcoming release. It will be fast-forwarded to dev as soon as 1.2.0 is released and/or work on 2.0.0 is started

**Comment by sruffell** [comment]
Thanks. Is there anything else I should do with this pull request then? It's still set to merge into dev, but the name is odd. Should I fix the name and resubmit or just leave it as is?

**Comment by lauft** [comment]
I do not see it necessary to rename it. Code looks good to me and it fixes #198 - so I will rebase and merge it.

**Pull request merged**
