### PR TITLE
Use AtomicFile to commit files as a group

### LINKED ISSUE #155: Corrupts database when no disk space available
When there's no disk space available timewarrior throws an error message and corrupts the database. 
Freeing up space on the disk did not solve the issue.
After I started tracking events again, the database for the whole month was overwritten. 
It's not a huge issue for me, since I got backups, but for some people it might be. 

```
*** Error in `timew': double free or corruption (!prev): 0x00000000008e8440 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f6879cd07e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f6879cd937a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f6879cdd53c]
/lib/x86_64-linux-gnu/libc.so.6(fclose+0x103)[0x7f6879cc6363]
timew(_ZN4FileD1Ev+0x36)[0x474356]
timew(_ZN8DatabaseD1Ev+0xab)[0x4193eb]
timew(main+0x871)[0x417371]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f6879c79830]
timew(_start+0x29)[0x418be9]
======= Memory map: ========
00400000-004e6000 r-xp 00000000 fd:01 9450940                            /usr/local/bin/timew
006e6000-006e7000 r--p 000e6000 fd:01 9450940                            /usr/local/bin/timew
006e7000-006e9000 rw-p 000e7000 fd:01 9450940                            /usr/local/bin/timew
006e9000-006ea000 rw-p 00000000 00:00 0
008b0000-009d8000 rw-p 00000000 00:00 0                                  [heap]
7f6874000000-7f6874021000 rw-p 00000000 00:00 0
7f6874021000-7f6878000000 ---p 00000000 00:00 0
7f6879c59000-7f6879e19000 r-xp 00000000 fd:01 5505234                    /lib/x86_64-linux-gnu/libc-2.23.so
7f6879e19000-7f687a019000 ---p 001c0000 fd:01 5505234                    /lib/x86_64-linux-gnu/libc-2.23.so
7f687a019000-7f687a01d000 r--p 001c0000 fd:01 5505234                    /lib/x86_64-linux-gnu/libc-2.23.so
7f687a01d000-7f687a01f000 rw-p 001c4000 fd:01 5505234                    /lib/x86_64-linux-gnu/libc-2.23.so
7f687a01f000-7f687a023000 rw-p 00000000 00:00 0
7f687a023000-7f687a039000 r-xp 00000000 fd:01 5509644                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f687a039000-7f687a238000 ---p 00016000 fd:01 5509644                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f687a238000-7f687a239000 rw-p 00015000 fd:01 5509644                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f687a239000-7f687a341000 r-xp 00000000 fd:01 5505230                    /lib/x86_64-linux-gnu/libm-2.23.so
7f687a341000-7f687a540000 ---p 00108000 fd:01 5505230                    /lib/x86_64-linux-gnu/libm-2.23.so
7f687a540000-7f687a541000 r--p 00107000 fd:01 5505230                    /lib/x86_64-linux-gnu/libm-2.23.so
7f687a541000-7f687a542000 rw-p 00108000 fd:01 5505230                    /lib/x86_64-linux-gnu/libm-2.23.so
7f687a542000-7f687a6b4000 r-xp 00000000 fd:01 8914130                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f687a6b4000-7f687a8b4000 ---p 00172000 fd:01 8914130                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f687a8b4000-7f687a8be000 r--p 00172000 fd:01 8914130                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f687a8be000-7f687a8c0000 rw-p 0017c000 fd:01 8914130                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f687a8c0000-7f687a8c4000 rw-p 00000000 00:00 0
7f687a8c4000-7f687a8ea000 r-xp 00000000 fd:01 5505232                    /lib/x86_64-linux-gnu/ld-2.23.so
7f687aa7f000-7f687aabe000 rw-p 00000000 00:00 0
7f687aae8000-7f687aae9000 rw-p 00000000 00:00 0
7f687aae9000-7f687aaea000 r--p 00025000 fd:01 5505232                    /lib/x86_64-linux-gnu/ld-2.23.so
7f687aaea000-7f687aaeb000 rw-p 00026000 fd:01 5505232                    /lib/x86_64-linux-gnu/ld-2.23.so
7f687aaeb000-7f687aaec000 rw-p 00000000 00:00 0
7ffcec3bc000-7ffcec3de000 rw-p 00000000 00:00 0                          [stack]
7ffcec3fa000-7ffcec3fd000 r--p 00000000 00:00 0                          [vvar]
7ffcec3fd000-7ffcec3ff000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

```

### PR DESCRIPTION
**Pull request by sruffell**
~NOTE: This pull request contains the same change as #282 because it is needed to prevent failures in the test suite, but I have that one broken out separately because I believe it is less debatable.~ (PR 282 has now been merged now so this comment no longer applies.)

~I've looked at the libfiu to enable the tests, but it is going to take more time to get that wired in reliably than I will have this weekend.~ (libfiu tests are now added to CI in the debiantesting container)

Here you can see how I can manually test this change. You should be able to see that even when I ran out of space on the disk that the database was still consistent and as you would expect. 

```shell
$ sudo mount -t tmpfs -o size=36K tmpfs ~/.timewarrior
$ src/timew export
[
]
$ src/timew start tag1
Note: 'tag1' is a new tag.
Tracking tag1
  Started 2020-02-01T03:54:34
  Current                  34
  Total               0:00:00
$ src/timew start tag2
Recorded tag1
  Started 2020-02-01T03:54:34
  Ended                    36
  Total               0:00:02
Note: 'tag2' is a new tag.
Tracking tag2
  Started 2020-02-01T03:54:36
  Current                  36
  Total               0:00:00
$ dd if=/dev/urandom of=~/.timewarrior/fill
dd: writing to '/home/sruffell/.timewarrior/fill': No space left on device
49+0 records in
48+0 records out
24576 bytes (25 kB, 24 KiB) copied, 0.00134455 s, 18.3 MB/s
$ src/timew start tag3
Recorded tag2
  Started 2020-02-01T03:54:36
  Ended                 55:08
  Total               0:00:32
Note: 'tag3' is a new tag.
Tracking tag3
  Started 2020-02-01T03:55:08
  Current                  08
  Total               0:00:00
Unable to update database.
$ echo $?
255
$ src/timew summary

Wk Date       Day Tags   Start     End    Time   Total
W5 2020-02-01 Sat tag1 3:54:34 3:54:36 0:00:02
                  tag2 3:54:36       - 0:00:51 0:00:53

                                               0:00:53

Unable to update database.
$ src/timew undo
fclose error 28: No space left on device
$ rm ~/.timewarrior/fill
$ src/timew summary

Wk Date       Day Tags   Start     End    Time   Total
W5 2020-02-01 Sat tag1 3:54:34 3:54:36 0:00:02
                  tag2 3:54:36       - 0:01:28 0:01:30

                                               0:01:30

$ src/timew undo
Undo
$ src/timew summary

Wk Date       Day Tags   Start End    Time   Total
W5 2020-02-01 Sat tag1 3:54:34   - 0:01:37 0:01:37

                                           0:01:37
$ src/timew tags
Tag  Description
tag1 -
```

Closes #155

### CODE REVIEW

**Comment by sruffell** [comment]
One more note on this. I removed the 'lock' method from the AtomicFile interface. It seems to me like if we really want to have advisory locking, we might want to use a lockfile in the database directory to lock all files?

If the locks are in there currently because multiple instances of `timew` may be running simultaneously, the database should still be consistent because each instance will use it's own pid as part of setting the temporary name. The last instance to run "finalize_all" will win, but the database should stay consistent.

**Comment by lauft** [comment]
>... we might want to use a lockfile in the database directory to lock all files?

I estimate collisions between different `timew` instances should be rare, but if there are multiple `timew` instances accessing the same database, it makes sense to have a central lockfile to ensure no commit gets lost. 🤔 

The question is shall the `timew` instance wait (until timeout?) to get the lock or fail instantly?

**Comment by sruffell** [comment]
> The question is shall the `timew` instance wait (until timeout?) to get the lock or fail instantly?

I believe to fail instantly is best, since it should be an error on the part of the user.

**Comment by sruffell** [comment]
I did have some time last night to pick up with libfiu (and realized that my problem with it previously was that what was available in the APT repo did not have the same hook points as what was documented in the source. Once I built from the sources libfiu from sources and installed, I was seeing what I was expecting).

So, that being said, I did run into some other places in libshared that did not produce any errors that I was depending on. Most significantly, the [`File::copy ()`](https://github.com/GothenburgBitFactory/libshared/blob/0d4e31de757ea2609a82549c5b09703d3d3fbe16/src/FS.cpp#L823-L836) function can fail to copy the source file without producing and error or exceptions, which could potentially cause problems with the `AtomicFile::append ()` function.

Below is the copy function that returns true even if the write into the destination fails:
```cpp
bool File::copy (const std::string& from, const std::string& to)
{
  // 'from' must exist.
  if (! access (from.c_str (), F_OK))
  {
    std::ifstream src (from, std::ios::binary);
    std::ofstream dst (to,   std::ios::binary);

    dst << src.rdbuf ();
    return true;
  }

  return false;
}
```

In practice, I didn't see any errors with the database corruption when I was limiting the filesystem size since one of the subsequent write failures that do throw on errors would prevent the rename for all the files.

So once I have time to fully update the tests, I believe there will at least need to be an update to the libshared submodule, but the change as is still vastly closes the opportunity for lack of space in the timewarrior database from corrupting the database.

**Comment by lauft** [comment]
Thanks for looking into this.

For the libshared issue I would ask you to open a separate issue/PR there. With `libfiu` please consider that the tests have to be set up and run on the Travis containers as well.

**Comment by sruffell** [comment]
> Thanks for looking into this.
> 
> For the libshared issue I would ask you to open a separate issue/PR there. 

I opened GothenburgBitFactory/libshared#21 for this issue. I'll update this pull request when that is merged.

> With `libfiu` please consider that the tests have to be set up and run on the Travis containers as well.

👍 Although it may be awhile before I can whip the tests into shape since I'll need to update the docker scripts to fetch and build [`libfiu`](https://github.com/albertito/libfiu) from source.

I thin this PR still could be a candidate in advance of automated tests since it can be hand validated by mounting the database onto a constrained tmpfs.

**Comment by sruffell** [comment]
Besides rewording some of the commit messages, I've: 

* Added a general test to make sure all the database files are unchanged after a random failure of one of the write system calls.

* Added code to automatically regenerate the tags database if parsing fails for any reason (which simplified things when I was making sure the test would catch failures when I swapped AtomicFiles back to Files)

* Updated the docker CMDs to make sure they return non-zero values if `./problems` returns any failures.

**Pull request merged**
