### PR TITLE
Adding completion for fish shell 

### PR DESCRIPTION
**Pull request by pfmephisto**
This is maybe not the cleanest way to write the completion, 
but I thought I'd start by contributing what I have so far for the fish shell.

### CODE REVIEW

**Comment by lauft** [comment]
Thank you for your contribution! ❤️ 
Would it be possible for you to provide also further maintenance for this completion? I.e. create a repository for this completion from which Timewarrior would draw regular updates, just like it is done for the [bash completion](https://github.com/lauft/timew-bashcompletion).

**Comment by pfmephisto** [comment]
Hi @lauft,
you're very welcome. I'm probably not the one most knolegeble on the topic and wrote it mostly for myself. But looking at the lack of other volunteers. Sure, I can set up a repository and manage changes and pull requests should they come in. 😃

**Comment by lauft** [comment]
@pfmephisto I have merged the PR now, but I am still hoping to hear from your repository 🙂

**Comment by pfmephisto** [comment]
@lauft, sorry, I got a bit sidetracked the past weekends.
I have now set up a repo [here](https://github.com/pfmephisto/timew-fishcompletion)
Let me know if I should change anything.

**Comment by lauft** [comment]
> Let me know if I should change anything.

@pfmephisto I think everything needed is here. 👍🏻 
I have updated the [README.md](https://github.com/GothenburgBitFactory/timewarrior/blob/develop/completion/README.md) accordingly. Thanks again!

**Pull request merged**
