### PR TITLE
#212: "--help" should show help, not considered to be a tag.

### PR DESCRIPTION
**Pull request by sruffell**
This change makes any instance of '--help' on the command line to be made the
command for this particular invocation.

Also note, this isn't something I hit very often but just wanted to take the opportunity to use the issue to learn another part of the code since I use timewarrrior every day.

### CODE REVIEW

**Comment by sruffell** [comment]
It is not clear to me if the checks that have failed are problems with the checks or with my proposed change.

**Comment by lauft** [comment]
I think those failed because of infrastructure problems: the build for gentoo seems to stall at the setup phase and the ubuntu build broke because a test assumed it would run before 11:59pm (and somehow it did not).

**Comment by lauft** [comment]
Thanks for your contribution!

**Comment by lauft** [comment]
I am going to extend this even one step further and will include `-h` as well

**Pull request merged**
