### PR TITLE
Allow to configure a default value for <range> in report command

### PR DESCRIPTION
**Pull request by chrko**
This addresses #394 which was recently opened by me.

TODOs:
* test(s)
* extend documentation

### CODE REVIEW

**Comment by lauft** [comment]
Thanks for your contribution. I will review it as soon as possible.

Btw.: Do you still plan to add tests? They were on your TODO-list...

**Comment by chrko** [comment]
@lauft Depends :D I haven't checked the testsuite yet how much effort this will be to test. If you consider this ready to merge, I would create a dedicated issue / pull request and start to work on a test case.

**Comment by lauft** [comment]
There is no hurry, so I would prefer to have this PR complete with tests. I will try to come up with some pointers, else feel free to ask.

**Comment by chrko** [comment]
I starting with the following approach to use `self.t.faketime(…)` to ensure always a consistent output, but this fails due the fact that faketime is not installed. Any hint how to proceed?

```diff
diff --git a/test/extensions.t b/test/extensions.t
index bda4ab9..a662c26 100755
--- a/test/extensions.t
+++ b/test/extensions.t
@@ -56,6 +56,19 @@ class TestExtensions(TestCase):
         code, out, err = self.t('report ext')
         self.assertIn('test works', out)
 
+    def test_default_range(self):
+        self.t.add_default_extension('debug')
+        self.t.faketime('2006-01-02T15:04')
+
+        self.t.config('reports.debug.range', 'today')
+
+        code, out, err = self.t('report debug')
+
+        self.assertIn('temp.report.start', out)
+
+        print(out)
+
+
 
 if __name__ == "__main__":
     from simpletap import TAPTestRunner
diff --git a/test/test_extensions/debug b/test/test_extensions/debug
new file mode 100755
index 0000000..d868679
--- /dev/null
+++ b/test/test_extensions/debug
@@ -0,0 +1,2 @@
+#!/bin/sh
+exec cat
```

**Comment by lauft** [comment]
Do not use faketime, but instead relative datetimes. For example, see `test/delete.t:46`

**Comment by lauft** [comment]
This has been implemented in 5265b26e.

**Pull request closed without merging**
